name: Tests template generation without executing tasks
on:
  workflow_call:
  push:
    branches:
      - "*"

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Run tests
        run: make test-template-no-tasks
  tests-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Run tests
        run: make test-template-no-tasks
