name: Tests template generation with tasks
on:
  workflow_call:
  pull_request:
    types: [opened, reopened, review_requested, ready_for_review]
  push:
    branches:
      - "main"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]"

concurrency:
  group: test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version-file: "template/.python-version"
          enable-cache: true
      - name: Run tests
        run: make test-template
